FROM maven:3.8.4-openjdk-17 AS builder
WORKDIR /app
COPY ./src ./src
COPY ./pom.xml .
RUN mvn clean package

FROM eclipse-temurin:17-jre-alpine
VOLUME /tmp
ARG JAR_FILE=target/*.jar
COPY --from=builder /app/target/*.jar gateway-service.jar
ENTRYPOINT ["java","-jar","/gateway-service.jar"]
